### ISSUE TITLE
pluging compatibility issue with latest dokuwiki release

### ISSUE THREAD

**Issue by G00364778** [marklundeberg/dokuwiki-plugin-latex#13]
There seems to be a data format compatibility breaking issue in the plugin introduced by the latest development upgrades on the wiki. I tried to figure out the details but cannot get beyond this point figuring out where in breaks in the plugin code.  

Any plans to update this or will this plugin become redundant now?

Thanks

[error] 23596#23596: *2957892 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of syntax_plugin_latex_common::render($mode, &$renderer, $data) must be compatible with dokuwiki\Extension\SyntaxPlugin::render($format, Doku_Renderer $renderer, $data) in /var/www/html/lib/plugins/latex/latexinc.php on line 0" while reading upstream, client:  request: "GET /latest/dynamic/instance-identity/document HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "[::ffff:a]"

**Comment by df8oe** [comment]
I can confirm this bug.

**Comment by lfmunoz** [comment]
anyone know how to fix this ? 

I mostly got this working by just doing what the error says:

"render($mode, &$renderer, $data) must be compatible with dokuwiki\Extension\SyntaxPlugin::render($format, Doku_Renderer $renderer, $data) in /var/www/html/lib/plugins/latex/latexinc.php"

So go into 

 /var/www/html/lib/plugins/latex/latexinc.php

and change render($mode, &$renderer, $data)   to render($format, Doku_Renderer $renderer, $data)

The syntax &$renderer must all change to Doku_Renderer $renderer in the following files:
```
usr/share/nginx/wiki/lib/plugins/latex/latexinc.php
    /usr/share/nginx/wiki/lib/plugins/latex/syntax/ddollar.php
   /usr/share/nginx/wiki/lib/plugins/latex/syntax/displaymath.php
    /usr/share/nginx/wiki/lib/plugins/latex/syntax/dollar.php
    /usr/share/nginx/wiki/lib/plugins/latex/syntax/eqnarray.php
   /usr/share/nginx/wiki/lib/plugins/latex/syntax/eqnarraystar.php
  /usr/share/nginx/wiki/lib/plugins/latex/syntax/equation.php
```
Also add this method to latexinc.php.
```
        function handle($match, $state, $pos, Doku_Handler $handler) {
                return array($match, $state, $pos);
        }

```
 No idea why I've never programmed with PHP or doku, it is just what is required by the skeleton example. And I did this and my doku wiki now works the latex is being displayed. 

The documentation here explains how it should work https://www.dokuwiki.org/devel:syntax_plugins

**Comment by BalticPinguin** [comment]
Hi @lfmunoz ,
thank you very much for sharing this!

I have two questions on this: First, you started with the version from this site, I guess!? There is a fork which is more up to date by [fsi-hska](https://github.com/fsi-hska/dokuwiki-plugin-latex), which is the branch where the plugins page links at.
Would you mind making a PR for this? I think, this would be a big benefit for many people!

*edit:* when downloading the fsi-hska version, all I had to do was to add the ``handle`` function as suggested by lfmunoz.

**Comment by G00364778** [comment]
one of the brach owners need to fix this or one of us need to branch it again apply all the fixes and
